import { describe, expect, it } from 'vitest';
import { NativeTurn } from './turn';
import { CodexTransport } from './transport';
import { asNativeSessionId, asSpecOpsTurnId } from '../../../src/lib/session/ids';
import type { ThreadItem } from './generated/v2/ThreadItem';
import type { SessionEvent } from '../../../src/lib/session/events';
function setup(secrets: string[] = []) { const transport = new CodexTransport('/missing','/missing'); let seq = 0; const turn = new NativeTurn({native:{runtimeId:'codex',connectionProfileId:'profile',nativeSessionId:asNativeSessionId('parent')},turnId:asSpecOpsTurnId('local'),workspaceRootPath:'/work',prompt:''},transport,()=>++seq,undefined,secrets);turn.bind('native');return turn; }
const collab = (state: string, tool = 'spawnAgent', status = 'completed') => ({type:'collabAgentToolCall',id:'item-'+state,tool,status,senderThreadId:'parent',receiverThreadIds:['child'],prompt:'Explore',model:null,reasoningEffort:null,agentsStates:{child:{status:state,message:'Result'}}}) as ThreadItem;
async function finish(turn: NativeTurn) { turn.finish('turn.finished');const events: SessionEvent[]=[];for await(const e of turn.events())events.push(e);return events; }
describe('native structured activity',()=>{
 it.each(['pendingInit','running','interrupted','completed','errored','shutdown','notFound'])('preserves child %s independently of completed spawn tool',async state=>{const turn=setup();turn.item(collab(state),true);const events=await finish(turn);const e=events.find(e=>e.type==='subtask.updated');expect(e?.type==='subtask.updated'&&e.subtask.status).toBe(({pendingInit:'pending',running:'running',interrupted:'interrupted',completed:'completed',errored:'failed',shutdown:'shutdown',notFound:'not-found'} as Record<string,string>)[state]);expect(events.some(e=>e.type==='tool.completed')).toBe(false);});
 it('uses exact native activity lifecycle, terminal unknown for unfinished states, distinct context events',async()=>{const turn=setup();turn.item(collab('running'),true);turn.item({type:'subAgentActivity',id:'activity',kind:'interrupted',agentThreadId:'child',agentPath:'worker'},true);turn.item({type:'contextCompaction',id:'context'},false);const events=await finish(turn);expect(events.filter(e=>e.type==='subtask.updated').at(-1)).toMatchObject({subtask:{id:'agent:child',status:'interrupted',agentPath:'worker'}});expect(events.filter(e=>e.type==='context.compaction').at(-1)).toMatchObject({subtask:{status:'unknown'}});expect(events.some(e=>e.type==='compaction.applied')).toBe(false);});
 it('masks opaque selected-profile credentials before truncation and split stream projection',async()=>{const secret='opaque credential canary value';const turn=setup([secret]);turn.item({...collab('completed'),prompt:secret,agentsStates:{child:{status:'completed',message:secret}}} as ThreadItem,true);turn.notification('item/agentMessage/delta',{threadId:'parent',turnId:'native',itemId:'text',delta:'safe '+secret.slice(0,12)},0);turn.notification('item/agentMessage/delta',{threadId:'parent',turnId:'native',itemId:'text',delta:secret.slice(12)+' tail'},0);turn.item({type:'agentMessage',id:'text',text:'x'.repeat(512*1024-8)+secret} as ThreadItem,true);const encoded=JSON.stringify(await finish(turn));expect(encoded).not.toContain(secret);expect(encoded).not.toContain('opaque c');expect(encoded).toContain('[redacted]');});
 it.each(['foreign-sender','unknown-state','secret-identity','oversized-children','oversized-path'])('rejects %s projection',kind=>{const turn=setup(['opaque-secret-id']);let value:any=collab('running');if(kind==='foreign-sender')value.senderThreadId='foreign';if(kind==='unknown-state')value.agentsStates.child.status='__proto__';if(kind==='secret-identity')value.receiverThreadIds=['opaque-secret-id'];if(kind==='oversized-children')value.receiverThreadIds=Array(65).fill('child');if(kind==='oversized-path')value={type:'subAgentActivity',id:'activity',kind:'started',agentThreadId:'child',agentPath:'x'.repeat(4097)};expect(()=>turn.item(value,true)).toThrow();turn.finish('turn.failed');});
 it('ignores late mismatched turn and generation native activity',async()=>{const turn=setup();for(const [turnId,generation] of [['other',0],['native',1]] as const)turn.notification('item/completed',{threadId:'parent',turnId,item:collab('completed')},generation);expect((await finish(turn)).some(e=>e.type==='subtask.updated')).toBe(false);});
});

it('near-capacity unfinished activity finalization fails once instead of silently emitting success',async()=>{const turn=setup();turn.item(collab('running'),true);for(let i=0;i<4094;i++)turn.emit({type:'diagnostic',level:'info',message:'buffered'});const events=await finish(turn);expect(events.filter(e=>['turn.finished','turn.failed','turn.cancelled'].includes(e.type))).toHaveLength(1);expect(events.at(-1)?.type).toBe('turn.failed');});
it('ordinary short environment flags do not corrupt native identity while opaque credentials remain masked',async()=>{
 const {nativeConfigCredentials}=await import('./ecosystem');const values=nativeConfigCredentials({mcp_servers:{server:{env:{PYTHONUNBUFFERED:'1',PORT:'3000',CUSTOM:'opaque-custom-canary'},http_headers:{Authorization:'opaque-header-canary'}}}});expect(values).not.toContain('1');expect(values).not.toContain('3000');const turn=setup(values);turn.item({...collab('completed'),receiverThreadIds:['child-1'],agentsStates:{'child-1':{status:'completed',message:'opaque-custom-canary opaque-header-canary'}}} as ThreadItem,true);const events=await finish(turn);expect(events.find(e=>e.type==='subtask.updated')).toMatchObject({subtask:{nativeThreadId:'child-1',output:'[redacted] [redacted]'}});
});

it('long single-atom credentials retain progressive safe normal deltas before terminal',async()=>{const turn=setup(['opaque.'+'x'.repeat(1800)]);turn.notification('item/agentMessage/delta',{threadId:'parent',turnId:'native',itemId:'text',delta:'Normal safe progressive text '},0);const iterator=turn.events()[Symbol.asyncIterator]();await iterator.next();expect(await iterator.next()).toMatchObject({value:{type:'text.delta',delta:'Normal safe progressive text '}});turn.finish('turn.finished');while(!(await iterator.next()).done){} });
