import type { CommandDefinition } from "../domain/contracts";

export const commandDefinitions: CommandDefinition[] = [
  {
    id: "app.toggleThemePane",
    label: "Themes",
    menuPath: "SpecOps/Themes",
    binding: { mac: "Cmd+Shift+,", windows: "Ctrl+Shift+," },
  },
  {
    id: "app.toggleSettings",
    label: "Settings",
    menuPath: "SpecOps/Settings",
    binding: { mac: "Cmd+,", windows: "Ctrl+," },
  },
  {
    id: "app.newWindow",
    label: "New Window",
    menuPath: "File/New Window",
    binding: { mac: "Cmd+Shift+N", windows: "Ctrl+Shift+N" },
  },
  {
    id: "view.cycleTheme",
    label: "Cycle Theme",
    menuPath: "View/Theme",
    binding: { mac: "Cmd+Shift+T", windows: "Ctrl+Shift+T" },
  },
  {
    id: "app.toggleFindReplace",
    label: "Find / Replace",
    menuPath: "Edit/Find Replace",
    binding: { mac: "Cmd+F", windows: "Ctrl+F" },
  },
  {
    id: "app.toggleGoTo",
    label: "Go To Line",
    menuPath: "Edit/Go To",
    binding: { mac: "Cmd+L", windows: "Ctrl+L" },
  },
  {
    id: "view.toggleMarkdownPreview",
    label: "Markdown Preview",
    menuPath: "Hidden/Markdown Preview",
    binding: { mac: "Cmd+Shift+M", windows: "Ctrl+Shift+M" },
  },
  {
    id: "view.toggleDiffPreview",
    label: "Diff Preview",
    menuPath: "View/Diff Preview",
    binding: { mac: "Cmd+Shift+D", windows: "Ctrl+Shift+D" },
  },
  {
    id: "file.new",
    label: "New Tab",
    menuPath: "File/New",
    binding: { mac: "Cmd+N", windows: "Ctrl+N" },
  },
  {
    id: "file.open",
    label: "Open File",
    menuPath: "File/Open",
    binding: { mac: "Cmd+O", windows: "Ctrl+O" },
  },
  {
    id: "file.openRecent",
    label: "Open Recent File",
    menuPath: "Hidden/Open Recent File",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.clearRecentFiles",
    label: "Clear Recent Files",
    menuPath: "File/Open Recent/Clear Recent",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.openAllInFolder",
    label: "Open all in Folder",
    menuPath: "File/Open all in Folder",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "workspace.add",
    label: "Add Workspace",
    menuPath: "File/Add Workspace",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "workspace.close",
    label: "Close Workspace",
    menuPath: "Hidden/Close Workspace",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "workspace.reorder",
    label: "Reorder Workspace",
    menuPath: "Hidden/Reorder Workspace",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.save",
    label: "Save",
    menuPath: "File/Save",
    binding: { mac: "Cmd+S", windows: "Ctrl+S" },
  },
  {
    id: "file.saveAs",
    label: "Save As",
    menuPath: "File/Save As",
    binding: { mac: "Cmd+Alt+S", windows: "Ctrl+Alt+S" },
  },
  {
    id: "file.saveAll",
    label: "Save All",
    menuPath: "File/Save All",
    binding: { mac: "Cmd+Shift+S", windows: "Ctrl+Shift+S" },
  },
  {
    id: "file.rename",
    label: "Rename",
    menuPath: "File/Rename",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.reloadFromDisk",
    label: "Reload from Disk",
    menuPath: "File/Reload from Disk",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "tab.close",
    label: "Close Tab",
    menuPath: "Tab/Close",
    binding: { mac: "Cmd+W", windows: "Ctrl+W" },
  },
  {
    id: "tab.moveToNewWindow",
    label: "Move Tab To New Window",
    menuPath: "Tab/Move To New Window",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "tab.next",
    label: "Next Tab",
    menuPath: "Tab/Next",
    binding: { mac: "Cmd+Shift+]", windows: "Ctrl+Tab" },
  },
  {
    id: "tab.previous",
    label: "Previous Tab",
    menuPath: "Tab/Previous",
    binding: { mac: "Cmd+Shift+[", windows: "Ctrl+Shift+Tab" },
  },
  {
    id: "edit.undo",
    label: "Undo",
    menuPath: "Edit/Undo",
    binding: { mac: "Cmd+Z", windows: "Ctrl+Z" },
  },
  {
    id: "edit.redo",
    label: "Redo",
    menuPath: "Edit/Redo",
    binding: { mac: "Cmd+Shift+Z", windows: "Ctrl+Y" },
  },
  {
    id: "edit.indent",
    label: "Indent",
    menuPath: "Edit/Indent",
    binding: { mac: "Cmd+]", windows: "Ctrl+]" },
  },
  {
    id: "edit.outdent",
    label: "Outdent",
    menuPath: "Edit/Outdent",
    binding: { mac: "Cmd+[", windows: "Ctrl+[" },
  },
  {
    id: "edit.moveLineUp",
    label: "Move Line Up",
    menuPath: "Edit/Move Line Up",
    binding: { mac: "Alt+Up", windows: "Alt+Up" },
  },
  {
    id: "edit.moveLineDown",
    label: "Move Line Down",
    menuPath: "Edit/Move Line Down",
    binding: { mac: "Alt+Down", windows: "Alt+Down" },
  },
  {
    id: "edit.duplicateLine",
    label: "Duplicate Line",
    menuPath: "Edit/Duplicate Line",
    binding: { mac: "Cmd+D", windows: "Ctrl+D" },
  },
  {
    id: "edit.joinLines",
    label: "Join Lines",
    menuPath: "Edit/Join Lines",
    binding: { mac: "Cmd+J", windows: "Ctrl+J" },
  },
  {
    id: "view.toggleWrap",
    label: "Toggle Wrap",
    menuPath: "View/Toggle Wrap",
    binding: { mac: "Cmd+Alt+Z", windows: "Ctrl+Alt+Z" },
  },
  {
    id: "view.zoomIn",
    label: "Zoom In",
    menuPath: "View/Zoom In",
    binding: { mac: "Cmd+=", windows: "Ctrl+=" },
  },
  {
    id: "view.zoomOut",
    label: "Zoom Out",
    menuPath: "View/Zoom Out",
    binding: { mac: "Cmd+-", windows: "Ctrl+-" },
  },
  {
    id: "view.zoomReset",
    label: "Reset Zoom",
    menuPath: "View/Reset Zoom",
    binding: { mac: "Cmd+0", windows: "Ctrl+0" },
  },
];
