import type { CommandDefinition } from "../domain/contracts";

export const commandDefinitions: CommandDefinition[] = [
  {
    id: "app.toggleThemePane",
    label: "Themes",
    menuPath: "SpecOps/Themes",
    category: "App",
    searchTerms: ["appearance", "color"],
    paletteIntent: "palette",
    binding: { mac: "Cmd+Shift+,", windows: "Ctrl+Shift+," },
  },
  {
    id: "app.toggleSettings",
    label: "Settings",
    menuPath: "SpecOps/Settings",
    category: "App",
    searchTerms: ["preferences", "options"],
    paletteIntent: "palette",
    binding: { mac: "Cmd+,", windows: "Ctrl+," },
  },
  {
    id: "app.openWorkspaceManager",
    label: "Workspace Manager",
    menuPath: "SpecOps/Workspace Manager",
    category: "App",
    searchTerms: ["workspaces"],
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "app.openVersionControl",
    label: "Version Control",
    menuPath: "SpecOps/Version Control",
    category: "App",
    searchTerms: ["git", "vc"],
    paletteIntent: "palette",
    availability: "workspace",
    binding: { mac: "Cmd+Shift+G", windows: "Ctrl+Shift+G" },
  },
  {
    id: "app.newWindow",
    label: "New Window",
    menuPath: "File/New Window",
    category: "File",
    paletteIntent: "palette",
    binding: { mac: "Cmd+Shift+N", windows: "Ctrl+Shift+N" },
  },
  {
    id: "view.cycleTheme",
    label: "Cycle Theme",
    menuPath: "View/Theme",
    category: "View",
    searchTerms: ["theme"],
    paletteIntent: "palette",
    binding: { mac: "Cmd+Shift+T", windows: "Ctrl+Shift+T" },
  },
  {
    id: "app.toggleFindReplace",
    label: "Find / Replace",
    menuPath: "Edit/Find Replace",
    category: "Edit",
    searchTerms: ["search"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+F", windows: "Ctrl+F" },
  },
  {
    id: "app.toggleGoTo",
    label: "Go To Line",
    menuPath: "Edit/Go To",
    category: "Navigation",
    searchTerms: ["jump", "line"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+L", windows: "Ctrl+L" },
  },
  {
    id: "app.findInProject",
    label: "Find in Project",
    menuPath: "Edit/Find in Project",
    category: "Edit",
    searchTerms: ["search workspace"],
    paletteIntent: "palette",
    availability: "workspace",
    binding: { mac: "Cmd+Shift+F", windows: "Ctrl+Shift+F" },
  },
  {
    id: "app.replaceInProject",
    label: "Replace in Project",
    menuPath: "Edit/Replace in Project",
    category: "Edit",
    paletteIntent: "palette",
    availability: "workspace",
    binding: { mac: "Cmd+Shift+R", windows: "Ctrl+Shift+R" },
  },
  {
    id: "app.quickOpenFile",
    label: "Quick Open",
    menuPath: "File/Quick Open",
    category: "File",
    searchTerms: ["go to file", "fuzzy", "find file"],
    paletteIntent: "palette",
    availability: "workspace",
    binding: { mac: "Cmd+P", windows: "Ctrl+P" },
  },
  {
    id: "app.openCommandPalette",
    label: "Command Palette",
    menuPath: "Hidden/Command Palette",
    category: "Navigation",
    searchTerms: ["commands", "actions"],
    paletteIntent: "exclude",
    paletteExcludeReason: "Already the command palette.",
    binding: { mac: "Cmd+Shift+P", windows: "Ctrl+Shift+P" },
  },
  {
    id: "app.toggleMarkdownOutline",
    label: "Toggle Markdown Outline",
    menuPath: "View/Markdown Outline",
    category: "View",
    searchTerms: ["headings", "toc", "structure"],
    paletteIntent: "palette",
    availability: "markdownEdit",
    binding: { mac: "Cmd+Shift+O", windows: "Ctrl+Shift+O" },
  },
  {
    id: "app.focusMarkdownOutline",
    label: "Focus Markdown Outline",
    menuPath: "Hidden/Focus Markdown Outline",
    category: "Navigation",
    searchTerms: ["headings", "toc", "structure"],
    paletteIntent: "palette",
    availability: "markdownEdit",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "view.toggleMarkdownPreview",
    label: "Markdown Preview",
    menuPath: "Hidden/Markdown Preview",
    category: "View",
    searchTerms: ["preview", "md"],
    paletteIntent: "palette",
    availability: "markdown",
    binding: { mac: "Cmd+Shift+M", windows: "Ctrl+Shift+M" },
  },
  {
    id: "view.toggleDiffPreview",
    label: "Diff Preview",
    menuPath: "View/Diff Preview",
    category: "View",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Shift+D", windows: "Ctrl+Shift+D" },
  },
  {
    id: "file.new",
    label: "New Tab",
    menuPath: "File/New",
    category: "File",
    paletteIntent: "palette",
    binding: { mac: "Cmd+N", windows: "Ctrl+N" },
  },
  {
    id: "file.open",
    label: "Open File",
    menuPath: "File/Open",
    category: "File",
    paletteIntent: "palette",
    binding: { mac: "Cmd+O", windows: "Ctrl+O" },
  },
  {
    id: "file.openRecent",
    label: "Open Recent File",
    menuPath: "Hidden/Open Recent File",
    category: "File",
    paletteIntent: "exclude",
    paletteExcludeReason: "Opened via Open Recent submenu paths, not a standalone palette action.",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.clearRecentFiles",
    label: "Clear Recent Files",
    menuPath: "File/Open Recent/Clear Recent",
    category: "File",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.openAllInFolder",
    label: "Open all in Folder",
    menuPath: "File/Open all in Folder",
    category: "File",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "workspace.add",
    label: "Add Workspace",
    menuPath: "File/Add Workspace",
    category: "Workspace",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "workspace.close",
    label: "Close Workspace",
    menuPath: "Hidden/Close Workspace",
    category: "Workspace",
    paletteIntent: "palette",
    availability: "workspace",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "workspace.reorder",
    label: "Reorder Workspace",
    menuPath: "Hidden/Reorder Workspace",
    category: "Workspace",
    paletteIntent: "exclude",
    paletteExcludeReason: "Payload-driven reorder from the workspace list UI only.",
    availability: "hidden",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.save",
    label: "Save",
    menuPath: "File/Save",
    category: "File",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+S", windows: "Ctrl+S" },
  },
  {
    id: "file.saveAs",
    label: "Save As",
    menuPath: "File/Save As",
    category: "File",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Alt+S", windows: "Ctrl+Alt+S" },
  },
  {
    id: "file.saveAll",
    label: "Save All",
    menuPath: "File/Save All",
    category: "File",
    paletteIntent: "palette",
    binding: { mac: "Cmd+Shift+S", windows: "Ctrl+Shift+S" },
  },
  {
    id: "file.rename",
    label: "Rename",
    menuPath: "File/Rename",
    category: "File",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "file.reloadFromDisk",
    label: "Reload from Disk",
    menuPath: "File/Reload from Disk",
    category: "File",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "tab.close",
    label: "Close Tab",
    menuPath: "Tab/Close",
    category: "Tab",
    paletteIntent: "palette",
    binding: { mac: "Cmd+W", windows: "Ctrl+W" },
  },
  {
    id: "tab.moveToNewWindow",
    label: "Move Tab To New Window",
    menuPath: "Tab/Move To New Window",
    category: "Tab",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "tab.next",
    label: "Next Tab",
    menuPath: "Tab/Next",
    category: "Tab",
    paletteIntent: "palette",
    binding: { mac: "Cmd+Shift+]", windows: "Ctrl+Tab" },
  },
  {
    id: "tab.previous",
    label: "Previous Tab",
    menuPath: "Tab/Previous",
    category: "Tab",
    paletteIntent: "palette",
    binding: { mac: "Cmd+Shift+[", windows: "Ctrl+Shift+Tab" },
  },
  {
    id: "edit.undo",
    label: "Undo",
    menuPath: "Edit/Undo",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Z", windows: "Ctrl+Z" },
  },
  {
    id: "edit.redo",
    label: "Redo",
    menuPath: "Edit/Redo",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Shift+Z", windows: "Ctrl+Y" },
  },
  {
    id: "edit.indent",
    label: "Indent",
    menuPath: "Edit/Indent",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+]", windows: "Ctrl+]" },
  },
  {
    id: "edit.outdent",
    label: "Outdent",
    menuPath: "Edit/Outdent",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+[", windows: "Ctrl+[" },
  },
  {
    id: "edit.moveLineUp",
    label: "Move Line Up",
    menuPath: "Edit/Move Line Up",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Alt+Up", windows: "Alt+Up" },
  },
  {
    id: "edit.moveLineDown",
    label: "Move Line Down",
    menuPath: "Edit/Move Line Down",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Alt+Down", windows: "Alt+Down" },
  },
  {
    id: "edit.duplicateLine",
    label: "Duplicate Line",
    menuPath: "Edit/Duplicate Line",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Alt+D", windows: "Ctrl+Alt+D" },
  },
  {
    id: "edit.joinLines",
    label: "Join Lines",
    menuPath: "Edit/Join Lines",
    category: "Edit",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+J", windows: "Ctrl+J" },
  },
  {
    id: "edit.selectNextOccurrence",
    label: "Select Next Occurrence",
    menuPath: "Edit/Select Next Occurrence",
    category: "Edit",
    searchTerms: ["find", "match", "multi-cursor"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+D", windows: "Ctrl+D" },
  },
  {
    id: "edit.selectAllOccurrences",
    label: "Select All Occurrences",
    menuPath: "Edit/Select All Occurrences",
    category: "Edit",
    searchTerms: ["find", "match", "multi-cursor"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Shift+L", windows: "Ctrl+Shift+L" },
  },
  {
    id: "edit.skipOccurrence",
    label: "Skip Occurrence",
    menuPath: "Edit/Skip Occurrence",
    category: "Edit",
    searchTerms: ["find", "match"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "edit.undoOccurrence",
    label: "Remove Last Occurrence",
    menuPath: "Edit/Remove Last Occurrence",
    category: "Edit",
    searchTerms: ["find", "match", "remove", "cursor"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "edit.toggleFold",
    label: "Toggle Fold",
    menuPath: "Edit/Toggle Fold",
    category: "Edit",
    searchTerms: ["collapse", "folding"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Alt+.", windows: "Ctrl+Alt+." },
  },
  {
    id: "edit.fold",
    label: "Fold",
    menuPath: "Edit/Fold",
    category: "Edit",
    searchTerms: ["collapse", "folding"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Alt+[", windows: "Ctrl+Shift+[" },
  },
  {
    id: "edit.unfold",
    label: "Unfold",
    menuPath: "Edit/Unfold",
    category: "Edit",
    searchTerms: ["expand", "folding"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Alt+]", windows: "Ctrl+Shift+]" },
  },
  {
    id: "edit.foldAll",
    label: "Fold All",
    menuPath: "Edit/Fold All",
    category: "Edit",
    searchTerms: ["collapse", "folding"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Ctrl+Alt+[", windows: "Ctrl+Alt+[" },
  },
  {
    id: "edit.unfoldAll",
    label: "Unfold All",
    menuPath: "Edit/Unfold All",
    category: "Edit",
    searchTerms: ["expand", "folding"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Ctrl+Alt+]", windows: "Ctrl+Alt+]" },
  },
  {
    id: "edit.triggerCompletion",
    label: "Trigger Completion",
    menuPath: "Edit/Trigger Completion",
    category: "Edit",
    searchTerms: ["complete", "autocomplete", "words", "suggest"],
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Ctrl+Space", windows: "Ctrl+Space" },
  },
  {
    id: "view.toggleWrap",
    label: "Toggle Wrap",
    menuPath: "View/Toggle Wrap",
    category: "View",
    paletteIntent: "palette",
    availability: "document",
    binding: { mac: "Cmd+Alt+Z", windows: "Ctrl+Alt+Z" },
  },
  {
    id: "view.zoomIn",
    label: "Zoom In",
    menuPath: "View/Zoom In",
    category: "View",
    paletteIntent: "palette",
    binding: { mac: "Cmd+=", windows: "Ctrl+=" },
  },
  {
    id: "view.zoomOut",
    label: "Zoom Out",
    menuPath: "View/Zoom Out",
    category: "View",
    paletteIntent: "palette",
    binding: { mac: "Cmd+-", windows: "Ctrl+-" },
  },
  {
    id: "view.zoomReset",
    label: "Reset Zoom",
    menuPath: "View/Reset Zoom",
    category: "View",
    paletteIntent: "palette",
    binding: { mac: "Cmd+0", windows: "Ctrl+0" },
  },
  {
    id: "view.layoutSingle",
    label: "Layout: Single",
    menuPath: "View/Layout/Single",
    category: "View",
    searchTerms: ["pane"],
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "view.layoutCols2",
    label: "Layout: 2 Columns",
    menuPath: "View/Layout/2 Columns",
    category: "View",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "view.layoutRows2",
    label: "Layout: 2 Rows",
    menuPath: "View/Layout/2 Rows",
    category: "View",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "view.layoutRows3",
    label: "Layout: 3 Rows",
    menuPath: "View/Layout/3 Rows",
    category: "View",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "view.layoutGrid",
    label: "Layout: Grid",
    menuPath: "View/Layout/Grid",
    category: "View",
    paletteIntent: "palette",
    binding: { mac: "none", windows: "none" },
  },
  {
    id: "view.focusPane1",
    label: "Focus Pane 1",
    menuPath: "Hidden/Focus Pane 1",
    category: "Navigation",
    paletteIntent: "palette",
    binding: { mac: "Cmd+Alt+1", windows: "Ctrl+Alt+1" },
  },
  {
    id: "view.focusPane2",
    label: "Focus Pane 2",
    menuPath: "Hidden/Focus Pane 2",
    category: "Navigation",
    paletteIntent: "palette",
    availability: "pane2",
    binding: { mac: "Cmd+Alt+2", windows: "Ctrl+Alt+2" },
  },
  {
    id: "view.focusPane3",
    label: "Focus Pane 3",
    menuPath: "Hidden/Focus Pane 3",
    category: "Navigation",
    paletteIntent: "palette",
    availability: "pane3",
    binding: { mac: "Cmd+Alt+3", windows: "Ctrl+Alt+3" },
  },
  {
    id: "view.focusPane4",
    label: "Focus Pane 4",
    menuPath: "Hidden/Focus Pane 4",
    category: "Navigation",
    paletteIntent: "palette",
    availability: "pane4",
    binding: { mac: "Cmd+Alt+4", windows: "Ctrl+Alt+4" },
  },
  {
    id: "view.focusEditor",
    label: "Focus Editor",
    menuPath: "View/Focus Editor",
    category: "Navigation",
    paletteIntent: "palette",
    binding: { mac: "Cmd+Shift+E", windows: "Ctrl+Shift+E" },
  },
];
